### ISSUE TITLE
Graph Block Time Display

### ISSUE THREAD

**Issue by TheKitty** [adafruit/io-issues#14]
I have varied the amount of time in the field "HOURS OF HISTORY (0 FOR REALTIME)", initially 1 hour, then 12 hours.  The display time on the x-axis seems remained fixed at a bit over a minute.  I don't see behavior changing based on the changing the "hours of history" field.  Also the field is not scrollable to back history although I wouldn't expect that, I checked to see if there was history not visible.

My current feed update interval from my Yun is 10 seconds with a bit more for overhead.

**Comment by TheKitty** [comment]
Ok, update, now it's at 12 minutes.  As the Yun has been up about 24 hours, I'd tend to say the display time hasn't been dependent on feeds being received.  Maybe I need a bit of education on how the displayed time is figured.

**Comment by TheKitty** [comment]
Now I see that the time scale changes if a dashboard is "closed" (like going back to the list of dashboards or other parts of the Adafruit site) then the dashboard is reopened.  I think that this scale changing could cause users to not be able to interpret the data like they might think they should.

**Comment by jwcooper** [comment]
I'll see if I can fix the graph not pulling in the history after saving. Any records over 1000, and it will pull in every nth record in order to keep the number at about 1000 as well. The graphs can only show a reasonable number of data points. We'll update this logic over time, and it should be documented at least on the learning system. The graph will see some more updates as we go here too, the "HOURS OF HISTORY (0 FOR REALTIME)" really isn't that intuitive or easy to use yet.

**Comment by jwcooper** [comment]
Recent changes to the chart should have made this better. Using more dynamic time scale calculations with better display of date range. Will close this, but we can re-open if you're still seeing issues.
