### ISSUE TITLE
create group api does not work 

### ISSUE THREAD

**Issue by rahulbats** [adafruit/io-issues#172]
i tried the create group api 
https://io.adafruit.com/api/docs/#!/Groups/createGroup

this is the error on screen
"There was a problem in the JSON you submitted: unexpected token at 'test-group'"

**Comment by abachman** [comment]
From the error message, it sounds like you tried posting the name of the group as a standalone parameter, rather than as a value in a JSON object with the key being `name`. The docs aren't very clear about how requests should be formatted, sorry about that.

I've added an example argument to that page of the API documentation to show what a properly formatted JSON argument for that endpoint should look like. So now if you visit the page you should see: 
![screen shot 2017-05-15 at 3 16 26 pm](https://cloud.githubusercontent.com/assets/13002/26074953/952c516c-3981-11e7-90aa-9b7a2c4ac831.png)

If you're using a tool like cURL, you can also use form-encoded params, something like this will work too: 
```sh
$ curl -F 'name=New Group' -H "X-AIO-Key: b1234567890000000000000000000000" https://io.adafruit.com/api/v2/example/groups
```
which returns: 
```json
{"username":"example","owner":{"id":1,"username":"example"},"id":2,"key":"new-group","name":"New Group","description":null,"visibility":"private","created_at":"2017-05-15T19:24:04Z","updated_at":"2017-05-15T19:24:04Z","feeds":[]}
```
