### ISSUE TITLE
Suggestion: Use the feed key to send data, not the feed name

### ISSUE THREAD

**Issue by PatBoud** [adafruit/io-issues#20]
I am using Python to update sensor data on AIO.

Syntax is as follows: aio.send(feed-name, value)

Feed name is used in chart titles. This value may change over time, and may need to be formatted to look pretty. In my opinion, it makes the Python code cumbersome.

Example: aio.send("Swimming pool's temperature", 74)

It may also introduce problems with hyphens.

I'd rather use the feed key that looks more like a variable:

Example: aio.send("pool-temp", 74)

I tried using the feed key, but it created a new feed, with what I provided as a name.

Thanks!

PatBoud

**Comment by tdicola** [comment]
Thanks for raising the issue and providing all the details.  Let me check if it's just a quirk of how the python API works, or if it's a limitation in the /send REST API that it's using.  If it's a limitation in the REST API perhaps we could add a new overload like aio.send_key(key, value) to manually create and send a feed entry using the key.

**Comment by tdicola** [comment]
I took a little closer look and yeah it does look like the send API only works with a feed name.  However I did add a client.append API that's very similar to send and lets you add a new row to an existing feed (identified by name, key, or ID) in one call.  Internally the append call is just using the create_data call to add the feed item, but the syntax is simpler since it takes the value as a parameter instead of requiring a Data instance.

To try it out grab the python library code again and reinstall it (run `sudo python setup.py install --force` just to make sure it installs the latest version).  Then you can change your code from:
```
aio.send("Swimming pool's temperature", 74)
```
To:
```
aio.append("pool-temp", 74)
```

If you're curious you can see the documentation for the append function by running `pydoc Adafruit_IO.client`, but for convenience here it is:
```
     |  append(self, feed, value)
     |      Helper function to simplify adding a value to a feed.  Will append the
     |      specified value to the feed identified by either name, key, or ID.
     |      Returns a Data instance with details about the newly appended row of data.
     |      Note that unlike send the feed should exist before calling append.
```

Let me know if you run into any issues or have feedback, thanks!

**Comment by PatBoud** [comment]
Great, thank you!
I'll give this a try when I get my Pi back online! :)

**Comment by PatBoud** [comment]
Works great, my code looks cleaner this way.

Thank you!
