### ISSUE TITLE
Longer time history for line chart

### ISSUE THREAD

**Issue by bbx10** [adafruit/io-issues#31]
The line chart hours of history is set for 24 hours but the chart shows only 10-12 hours data on the X-axis. Samples are spaced 10 minutes apart so the number of samples is low. Is there a limit on the number samples per chart?

Line charts for 1 day, 7 days, and 28 days would be useful.

**Comment by jwcooper** [comment]
Thank you for the feedback. We're working on adding more features to the line chart, and better options like this is one of them.

Right now, I think the limit is set at 1000 data points for each chart, but we can increase it if the average computer/browser can handle it. The charts are generated on the fly in svg.

**Comment by ribico** [comment]
Hello, I created a line chart with 3 feeds and this is the result:
![schermata del 2016-01-29 14-35-31](https://cloud.githubusercontent.com/assets/5812335/12676884/9991524e-c695-11e5-92bb-e5016a96a71b.png)

you can notice that one line is drawn correctly for the whole time axis while the others are drawn only for the last 10 hours or so.

Data seems to available in the feed:
![schermata del 2016-01-29 14-37-53](https://cloud.githubusercontent.com/assets/5812335/12676947/f24b4944-c695-11e5-81ba-860b39194246.png)

Bu configuring a line chart with only those feeds creating the issue data is displayed for a shorted period than expected (I set 48 hours in settings).
![schermata del 2016-01-29 14-40-51](https://cloud.githubusercontent.com/assets/5812335/12677019/7516a1a2-c696-11e5-80f0-32acb9b7ee2c.png)

Is it always due to 1000 data points limit ?
Don't you think that rather than simply limiting number of data points a smoothing would be better ?
Something like having always 1000 data points in the set time period but calculated with an averaging filter on the whole set of available data.

**Comment by jwcooper** [comment]
Thanks for the feedback. We're tracking this internally now as well. Further issues or enhancement requests can go to our forum as we're consolidating our support and issues: https://forums.adafruit.com/viewforum.php?f=56
