### ISSUE TITLE
Deleted Data, deleted my account

### ISSUE THREAD

**Issue by churchja** [adafruit/io-issues#41]
I was trying to clear my data stream by using the "destroy data" button. However, it seemed to delete my account as well. Is this intentional? Recommend adding a warning if so... How to delete data without deleting your account? Thank you... Jason

**Comment by jwcooper** [comment]
This is intentional, it's a way to clear all data if you ever wanted to leave IO. That being said, I'm going to seperate this functionality into two buttons. One to destroy non-account data, and one to clear everything.

We currently due have a warning with the following text in the confirmation dialog:
This will delete all of the io.adafruit.com data (including the beta access and account information) associated with this account. This can not be reversed.

**Comment by jwcooper** [comment]
There are now two separate buttons on the /settings for destroying data.
