### ISSUE TITLE
Feature Request: iframe block

### ISSUE THREAD

**Issue by RyRutD** [adafruit/io-issues#47]
This block should be able to be given a link, and display the page on the dashboard in real time, kind of like the IFRAME in HTML.

**Comment by toddtreece** [comment]
@RyRutD we have discussed this, and i don't think we are going to be able to implement it at this point due to the security risks related to iframes. although there are methods to prevent iframe attacks, the risk isn't worth implementing the iframe block.

is there a missing IO feature that you planned to load via iframe? if so, feel free to open a new issue and we can look at adding it.
