### ISSUE TITLE
Feature request: publish data with specified timestamp

### ISSUE THREAD

**Issue by theschles** [adafruit/io-issues#75]
Hi all,

User @tapiralec on https://github.com/adafruit/Adafruit_MQTT_Library/issues/18 suggested I post here.

I'm gathering temperature, humidity, and light level readings for publishing to Adafruit IO via an Adafruit Huzzah (esp8266).  Right now I'm capturing all three readings once a second and then immediately publishing all three to separate feeds via the Adafruit MQTT Arduino library; this allows the displayed chart data for those three readings to be relatively up-to-date at all times.

The downside to all of this is that the WiFi part of the esp8266 is always on -- which drains the battery.  It would be great to be able to turn the WiFi off, store data in an array in memory with timestamps (probably seconds since last transfer), and then not turn the WiFi back on until either (a) memory is almost full or (b) battery almost gone -- at which time iterate through that data array and upload tuples of (created_at_timestamp, value).

User @jwcooper said "The plan is to add support for custom created_at timestamps from the REST API and from MQTT. This is fairly high on the list of things to do in order to begin supporting batch uploading of data."

Please oh please add this feature soon so I can make these batteries last longer.

Thanks

**Comment by andy-g** [comment]
:+1: 

I'd love to see this too, it also has the potential to take load off the servers as multiple readings would be uploaded in a single request.

**Comment by CharString** [comment]
Not just the timestamp...
To maximize the efficiency of these burst sends, ideally one would like to send one HTTP request in a 4k packet with as much data as possible.

In steps of efficiency:
Current takes 3 requests per sense timeframe (one for each sensor value):
```
POST to /feed/temp/data resource
{"value": "string"}
POST to /feed/hum/data resource
{"value": "string"}
POST to /feed/light/data resource
{"value": "string"}
```
Adding created_at_epoch, would bring this down to 3 requests per ~(free dram/value size):
```
POST to /feed/temp/data resource
[{"value": "string", "epoch": number}, ...]
POST to /feed/hum/data resource
[{"value": "string", "epoch": number}, ...]
POST to /feed/light/data resource
[{"value": "string", "epoch": number}, ...]
```
Adding a new resource on the server that allows to publish data to multiple streams at once would enable 1 http request to handle it, allowing for even more sleep:
```
POST to /data resource
{
  "temp": [{"value": "string", "epoch": number}, ...],
  "hum": [{"value": "string", "epoch": number}, ...],
  "light": [{"value": "string", "epoch": number}, ...]
}
```

Allowing "value", "lat", "lon" and "ele" to be numbers, would shrink the requests a couple of bytes for the *"*. And accepting msgpack would shrink them down even more.
Busy websites optimize for as little requests as they can, because visitor attention runs out even quicker than a LiPo battery: https://developer.yahoo.com/performance/rules.html#num_http=

Less request would be easier on the open connections on the server at the expense of some extra computation in handling the requests. When processing and storing the data will take too much time, returning a 202 response code upon reception and closing the connection is an option for low QoS feeds. Processing the data can then be fanned out to workers. And errors like malformed json/msgpack could be made available to the owner of the feeds via a side channel. Scalability FTW!

**Comment by tommck** [comment]
I too am looking to have minimally the ability to update the time stamp and/or upload many object as-is.

As the functionality is right now, it's not useful to me.

**Comment by the-louie** [comment]
I second this. I'm building small sensors with esp8266 that run on battery and measure every five minutes but transmits only every hour.

**Comment by jwcooper** [comment]
Thanks for the feedback. We're tracking this internally now as well. Further issues or enhancement requests can go to our forum as we're consolidating our support and issues: https://forums.adafruit.com/viewforum.php?f=56

**Comment by minexew** [comment]
Has this ever been implemented?

**Comment by jwcooper** [comment]
Yes, you can batch data with the API: https://io.adafruit.com/api/docs/#operation/batchCreateGroupFeedData
