### ISSUE TITLE
stream block timestamp format uses single digits

### ISSUE THREAD

**Issue by mgk** [adafruit/io-issues#82]
Example:

```
2015-11-30 9:2:15 - some-switch - closed
```

Should be:

```
2015-11-30 09:02:15 - some-switch - closed
```

**Comment by andreavalle** [comment]
I agree that this should be fixed. Thanks

**Comment by mgk** [comment]
Just curious. Was this fixed by a commit or PR not referenced here?

**Comment by abachman** [comment]
Hi @mgk! 

Sorry to close without comment. We're working on our rebuild of the Adafruit IO interface I was triaging issues, probably moving too quickly. Most will be fixed in the next big release but this one was a quick-fix on the current interface so I fixed, deployed, and closed the issue in one fell swoop. You won't see commits to the repo we deploy AIO from, but I could've dropped you a line before closing, my apologies.

Thanks for bringing up the issue, too, btw. We're still very focused on IO and having participation like this is a big help.

**Comment by mgk** [comment]
No worries at all, kind of guessed it was something like that. Just keeping you honest ;)
